// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL7QfY2kTpKynMBRWuHrLcF8qhLtCTlwI',
    appId: '1:536154905002:web:05689b291f4238b5af73d3',
    messagingSenderId: '536154905002',
    projectId: 'mygainz-2e0ac',
    authDomain: 'mygainz-2e0ac.firebaseapp.com',
    storageBucket: 'mygainz-2e0ac.firebasestorage.app',
    measurementId: 'G-H6BX3FJ53C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PdAup_FBsH-Yjm3ER5gcvZz5XjfXuig',
    appId: '1:536154905002:android:32bb40ddf59fe836af73d3',
    messagingSenderId: '536154905002',
    projectId: 'mygainz-2e0ac',
    storageBucket: 'mygainz-2e0ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC-ttT_a747qm7OhAQUx93R_7KY97cJQo',
    appId: '1:536154905002:ios:2bffd5f17e9957b2af73d3',
    messagingSenderId: '536154905002',
    projectId: 'mygainz-2e0ac',
    storageBucket: 'mygainz-2e0ac.firebasestorage.app',
    iosBundleId: 'io.github.MikeGonzaBar.mygainz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC-ttT_a747qm7OhAQUx93R_7KY97cJQo',
    appId: '1:536154905002:ios:2bffd5f17e9957b2af73d3',
    messagingSenderId: '536154905002',
    projectId: 'mygainz-2e0ac',
    storageBucket: 'mygainz-2e0ac.firebasestorage.app',
    iosBundleId: 'io.github.MikeGonzaBar.mygainz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL7QfY2kTpKynMBRWuHrLcF8qhLtCTlwI',
    appId: '1:536154905002:web:16e205bf5a77ccdfaf73d3',
    messagingSenderId: '536154905002',
    projectId: 'mygainz-2e0ac',
    authDomain: 'mygainz-2e0ac.firebaseapp.com',
    storageBucket: 'mygainz-2e0ac.firebasestorage.app',
    measurementId: 'G-QZ94PFR1NF',
  );
}
